$(function () {
﻿var listhtml=''; 
listhtml+='<div class="z-box-t"><span>&nbsp;</span></div>';
listhtml+='<div class="z-box-c">';
listhtml+='<div class="z-box-m">';
listhtml+='<div class="z-con">';
listhtml+='<div class="z-tree"> <span class="z-tree-bg">&nbsp;</span>';
listhtml+='<ul class="z-tree-root">';
listhtml+='<li class="z-tree-li">';
listhtml+='<h3><a href="#" class="z-tree-active">中企动力</a></h3>';
listhtml+='<ul style="display:block;" class="z-tree-ul">';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">ICT部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">IDC</a></li>';
listhtml+='<li class="z-tree-li">';
listhtml+='<h3><a href="#" class="z-tree-active">数字管理</a></h3>';
listhtml+='<ul style="display:block;" class="z-tree-ul">';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">UE研究部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">UE用户体验部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">交互设计部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">视觉设计部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">界面制作部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">可用性设计部</a></li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">测试部</a></li>';
listhtml+='</ul>';
listhtml+='</li>';
listhtml+='<li class="z-tree-li z-tree-leaf"><a href="#">质量管理部</a></li>';
listhtml+='</ul>';
listhtml+='</li>';
listhtml+='</ul>';
listhtml+='</div>';
listhtml+='</div>';
//listhtml+='<div>正在加载列表，请稍候…</div>';
listhtml+='</div>';
listhtml+='</div>';
listhtml+='<div class="z-box-b"><span>&nbsp;</span></div>';
$("#devicelist_div").html(listhtml);
});